# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hazem
      POSTGRES_DB: posts
      POSTGRES_PASSWORD: test123
